spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/client-contact-management
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #flyway:
  flyway:
    mixed: true
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/client-contact-management
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true
